name: Publish npm wrapper

on:
  push:
    branches: [main]
    paths:
      - 'vibe-annotations-npm/**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Check if version changed
        id: version_check
        run: |
          cd vibe-annotations-npm
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          
          # Check if this version is already published
          if npm view vibe-annotations-server@$CURRENT_VERSION version 2>/dev/null; then
            echo "Version $CURRENT_VERSION already published"
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "Version $CURRENT_VERSION not published yet"
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Publish to npm
        if: steps.version_check.outputs.should_publish == 'true'
        run: |
          cd vibe-annotations-npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}